Adatbazis_BB/WebApi/Controllers/CrudController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using BusinessLogic;
using WebApi.Models;

namespace WebApi.Controllers
{
    public class CrudController : Controller
    {
        private IMapper mapper;
        private ILogic logic;
        private CrudModel model;

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            mapper = DTO.AutoMapperConfig.GetMapper();

            logic = new RealLogic();
            model = new CrudModel();
            model.EditObject = new TranslaterModel();

            var tlist = logic.GetTranslaters();
            model.List = mapper.Map<IQueryable<Adatbazis_BB.TRANSLATER>, List<Models.TranslaterModel>>(tlist);

            base.OnActionExecuting(filterContext);
        }

        private TranslaterModel GetTranslaterModel(int id)
        {
            Adatbazis_BB.TRANSLATER t = logic.GetOneTranslater(id);
            return mapper.Map<Adatbazis_BB.TRANSLATER, Models.TranslaterModel>(t);
        }

        // GET: Crud
        public ActionResult Index()
        {
            ViewData["TargetAction"] = "AddNew";

            return View("CrudIndex", model);
        }

        public ActionResult Details(int id)
        {
            return View("CrudDatasheet", GetTranslaterModel(id));
        }
        public ActionResult Edit(int id)
        {
            ViewData["TargetAction"] = "EditAll";
            model.EditObject = GetTranslaterModel(id);
            return View("CrudIndex", model);
        }
        [HttpPost]
        public ActionResult EditAll(TranslaterModel model)
        {
            if (ModelState.IsValid && model != null)
            {
                logic.ModifyTranslaterAll(model.tranid, model.tname, model.tskill, model.tlanguage);
                TempData["result"] = "Edit OK";
            }
            else
            {
                TempData["result"] = "Edit FAIL";
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult EditLang(TranslaterModel model)
        {
            if (ModelState.IsValid && model != null)
            {
                logic.ModifyTranslaterLang(model.tranid, model.tskill, model.tlanguage);
                TempData["result"] = "Edit OK";
            }
            else
            {
                TempData["result"] = "Edit FAIL";
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult EditName(TranslaterModel model)
        {
            if (ModelState.IsValid && model != null)
            {
                logic.ModifyTranslaterName(model.tranid, model.tname);
                TempData["result"] = "Edit OK";
            }
            else
            {
                TempData["result"] = "Edit FAIL";
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult EditSkill(TranslaterModel model)
        {
            if (ModelState.IsValid && model != null)
            {
                logic.ModifyTranslaterSkill(model.tranid);
                TempData["result"] = "Edit OK";
            }
            else
            {
                TempData["result"] = "Edit FAIL";
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AddNew(TranslaterModel model)
        {
            if (ModelState.IsValid && model != null)
            {
                Adatbazis_BB.TRANSLATER t = mapper.Map<Models.TranslaterModel, Adatbazis_BB.TRANSLATER>(model);
                t.TRANID = logic.GetNextTransno();
                logic.AddTranslater(t);
                TempData["result"] = "Add OK";
            }
            else
            {
                TempData["result"] = "Add FAIL";
            }
            return RedirectToAction("Index");
        }
        public ActionResult Remove(int id)
        {
            try
            {
                logic.DelTrans(id);
                TempData["result"] = "Del OK";
            }
            catch (DbUpdateException)
            {
                TempData["result"] = "Del FAIL";
            }
            catch (ArgumentException)
            {
                TempData["result"] = "Del FAIL";
            }
            return RedirectToAction("Index");
        }
    }
}

Adatbazis_BB/WebApi/Views/Crud/CrudDatasheet.cshtml
@model WebApi.Models.TranslaterModel

@{
    ViewBag.Title = "CrudDatasheet";
}

<h2>CrudDatasheet</h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.tranid)</td>
        <td>@Html.DisplayFor(m => m.tranid)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.tname)</td>
        <td>@Html.DisplayFor(m => m.tname)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.tskill)</td>
        <td>@Html.DisplayFor(m => m.tskill)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.tlanguage)</td>
        <td>@Html.DisplayFor(m => m.tlanguage)</td>
    </tr>
</table>

Adatbazis_BB/WebApi/Views/Crud/CrudEdit.cshtml
@model WebApi.Models.TranslaterModel



<h2>Add/Edit Translater</h2>

@using (Html.BeginForm(ViewData["TargetAction"].ToString(), "Crud"))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.tranid)

    <div class="editor-label">@Html.LabelFor(m => m.tname)</div>
    <div class="editor-field">@Html.EditorFor(m => m.tname)</div>

    <div class="editor-label">@Html.LabelFor(m => m.tskill)</div>
    <div class="editor-field">@Html.EditorFor(m => m.tskill)</div>

    <div class="editor-label">@Html.LabelFor(m => m.tlanguage)</div>
    <div class="editor-field">@Html.EditorFor(m => m.tlanguage)</div>

    <input type="submit" value="SEND" />
}

Adatbazis_BB/WebApi/Views/Crud/CrudIndex.cshtml
@model WebApi.Models.CrudModel

@{
    ViewBag.Title = "CrudIndex";
}

<h2>CrudIndex</h2>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
}

<!-- ez a fő nézet, és kettő al nézetet fog összerakni-->
<!-- az első paraméter a nézet neve, a másik a nézet amit át akarok adni -->
@Html.Partial("CrudEdit", Model.EditObject)

@Html.Partial("CrudList", Model.List)

Adatbazis_BB/WebApi/Views/Crud/CrudList.cshtml
@model IEnumerable<WebApi.Models.TranslaterModel>

<p style="color:red">@TempData["result"]</p>

@if (Model.Count() == 0)
{
    <p>No data in DB!</p>
}
else
{
    <table>
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(m => m.tranid)</th>
                <th>@Html.DisplayNameFor(m => m.tname)</th>
                <th>@Html.DisplayNameFor(m => m.tskill)</th>
                <th>@Html.DisplayNameFor(m => m.tlanguage)</th>
                <th>Datasheet</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(m => item.tranid)</td>
                    <td>@Html.DisplayFor(m => item.tname)</td>
                    <td>@Html.DisplayFor(m => item.tskill)</td>
                    <td>@Html.DisplayFor(m => item.tlanguage)</td>
                    <td>@Html.ActionLink("Details", "Details", new { id = item.tranid })</td>
                    <td>@Html.ActionLink("Edit", "Edit", new { id = item.tranid })</td>
                    <td>@Html.ActionLink("Remove", "Remove", new { id = item.tranid })</td>
                </tr>
            }
        </tbody>
    </table>
}